### ISSUE TITLE
dispartiy between display web page and .html

### ISSUE THREAD

**Issue by davidjamesbeck** [paul-shannon/slexil#9]
I found that most of the rendering problems we were having had to do with the ELAN file we have for Inferno, so I started editing in .eaf. The first thing I did was replace some of the incorrect hyphens with colons. I had already gone through the steps in slexil once, but I started again at the beginning after editing the .eaf. The output was fine in the text.html file:

<img width="1176" alt="screen shot 2019-02-24 at 7 58 28 am" src="https://user-images.githubusercontent.com/43762566/53300897-05399900-380a-11e9-9cc8-b83fc9aa8d2f.png"> 

but in the "display web page" box in the app, I still see the original .eaf 

<img width="1032" alt="screen shot 2019-02-24 at 7 59 38 am" src="https://user-images.githubusercontent.com/43762566/53300913-2bf7cf80-380a-11e9-9fd0-351d688fcd3d.png">

I have cleared my cache in the browser, closed the browser window, and restarted webapp.py without managing to update the view. Does dash create some kind of cache of its own?  

I don't know if this is a "real" problem that users might have or just something annoying that happens during development, but if it is worth fixing and you have some idea of what is going on ...

**Comment by paul-shannon** [comment]
Could you commit and push your changes to inferno-threeLines.eaf?
Then I’ll check.

 - Paul

**Comment by davidjamesbeck** [comment]
done

**Comment by davidjamesbeck** [comment]
Okay, I think that this may have been my bad—I probably skipped over the "Create web page" button, so the "Display web page" might have been working with an old model of the .eaf (not sure where that would have existed after clearing the cache, shutting down the webapp, etc.) If I click the three buttons in strict sequence, the edits to the .eaf file do show up. However, we should probably consider either a) enforcing the strict sequence of button clicks by disabling later buttons until the new buttons are pressed or b) making the later buttons do the work of the earlier buttons if these haven't been pressed already (so a user could skip "create" and go straight to "display"). Actually, I wonder if users would ever want to "Create" as an independent step in the process? It's good for us in terms of debugging, but I imagine most people would want to go straight to "Display" or "Save"

**Comment by paul-shannon** [comment]
I completely agree.  The “CREATE WEB PAGE” button adds nothing.  Disabling inappropriate buttons is a good idea.

I think there is another problem.  Could you run a quick test?

Run all the steps.  Display the web page.  Then upcase “mezzo” to “MEZZO” in the eaf file.  Reload the eaf file (noting timestamp should have changed when you select the file).  Rerun the subsequent steps.

I still see “mezzo” - unless I, in the browser, reload the webapp.  No need to restart webapp.py.

I think this is caused by a feature/annoyance of React <https://dash.plot.ly/react-for-python-developers> - the javascript library dash uses - dash being our python library, which sits on top of flask, to provide all the back-and-forth between webpage and server.  

I’ll look into this.  Might not be hard, probably involves clearing some state so that dash/React knows to re-render that html.

Thanks for these reports, fixes, and suggestions!

 - Paul

**Comment by davidjamesbeck** [comment]
I had to quite the webapp. Even quitting the browser wasn’t enough.

**Comment by paul-shannon** [comment]
Odd.  Discouraging.  I’ll need to mull this over, create some tiny exploratory webapp with which to debug - probably not till next weekend.

 - Paul

**Comment by davidjamesbeck** [comment]
I would guess this to be less important than the download problem—if we do our other jobs right, users will not need to cycle back immediately between micro-edited version of their .eaf file.

I am adding a .py file (formatting.py) to the project to handle some of the rendering problems since some apply both to the morpheme and the morphemeGloss lines. It will make further fixes (like adding single quotes, eliminating illegal characters and whitespace,etc.) that much easier to manage with everything in one place. I may have a beginning of that ready to push by the end of the day.

David
